# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration file for Calamares
#
# This is the top-level configuration file for Calamares.
# It specifies what modules will be used, as well as some
# overall characteristics -- is this a setup program, or
# an installer. More specific configuration is devolved
# to the branding file (for the UI) and the individual
# module configuration files (for functionality).
---
# Modules can be job modules (with different interfaces) and QtWidgets view
# modules. They could all be placed in a number of different paths.
# "modules-search" is a list of strings, each of these can either be a full
# path to a directory or the keyword "local".
#
# "local" means:
#   - modules in $LIBDIR/calamares/modules, with
#   - settings in SHARE/calamares/modules or /etc/calamares/modules.
# In debug-mode (e.g. calamares -d) "local" also adds some paths
# that make sense from inside the build-directory, so that you
# can build-and-run with the latest modules immediately.
#
# Strings other than "local" are taken as paths and interpreted
# relative to wherever Calamares is started. It is therefore **strongly**
# recommended to use only absolute paths here. This is mostly useful
# if your distro has forks of standard Calamares modules, but also
# uses some form of upstream packaging which might overwrite those
# forked modules -- then you can keep modules somewhere outside of
# the "regular" module tree.
#
#
# YAML: list of strings.
modules-search: [ local ]

instances:
- id:       online
  module:   packages
  config:   packages_online.conf

#- id:       online
#  module:   welcome
#  config:   welcome_online.conf

- id:       before-online
  module:   shellprocess
  config:   shellprocess-before-online.conf

- id:       modify_mk_hook
  module:   shellprocess
  config:   shellprocess_modify_mk_hook.conf

- id:       reset_mk_hook
  module:   shellprocess
  config:   shellprocess_reset_mk_hook.conf

- id:       initialize_pacman
  module:   shellprocess
  config:   shellprocess_initialize_pacman.conf

- id:       removeucode
  module:   shellprocess
  config:   shellprocess_removeucode.conf

- id:       enable_ufw
  module:   shellprocess
  config:   shellprocess_enable_ufw.conf

- id:       parched
  module:   shellprocess
  config:   shellprocess_parched.conf


sequence:
- show:
  #- welcome@online
  - welcome
  - locale
  - keyboard
  - partition
#  - packagechooser
  - netinstall
  - users
  - summary
- exec:
  - partition
# - zfs from personal config
#  - zfs
  - mount
  - unpackfs
  #- shellprocess@modify_mk_hook
  #- shellprocess@initialize_pacman
  #- pacstrap
  - machineid
  - locale
  - keyboard
  - localecfg
  - chwd
  #- shellprocess@before-online
  - packages@online
  - luksbootkeyfile
  - luksopenswaphookcfg
  - fstab
#  - plymouthcfg this and zfshostid are uncommented in cachyos config
#  - zfshostid
  - initcpiocfg
  - initcpio
  - users
#  - networkcfg cachyos position
  - displaymanager
  - shellprocess@parched
  #- chwd
  - networkcfg
  - hwclock
  - services-systemd
  #- shellprocess@removeucode
  - grubcfg
  - bootloader
#  - shellprocess@reset_mk_hook
#  - services-systemd cachyos position
#  - shellprocess
#  - shellprocess@enable_ufw
  - shellprocessfinal
  - umount
- show:
  - finished

branding: manjaro

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: true

quit-at-end: false
